test:
    scheme:
        id:
            Hydrator\Strategy\EntityIdStrategy: _id
        groupId: group_id
        externalId: external_id
        booleanType:
            Hydrator\Strategy\BooleanStrategy: boolean_type
        datetime:
            Hydrator\Strategy\DateTimeStrategy: datetime
        floatType:
            Hydrator\Strategy\FloatStrategy: float_type
        numberType:
            Hydrator\Strategy\NumberStrategy: number_type
        methodType:
            Hydrator\Strategy\MethodStrategy: callMe
        objectType:
            Hydrator\Strategy\DefaultStrategy: object_type
        sub:
            ~subScheme: inner
        subArray:
            ~subScheme[]: innerArray
subScheme:
    scheme:
        Telephone: tel